# Ground Configuration for WORKWAY Cloudflare Monorepo
# https://github.com/create-something/ground
#
# Framework patterns are in .ground/*.yml for reusability

extends:
  - .ground/common.yml
  - .ground/sveltekit.yml
  - .ground/cloudflare-workers.yml

ignore:
  # ==========================================================================
  # PROJECT-SPECIFIC: Structural patterns across integrations
  # ==========================================================================
  functions:
    - getCapabilities      # Required interface method (13 integrations)
    - constructor          # Class initialization boilerplate
    - initialize           # Integration setup pattern
    - setWeights           # Router/Priority - different types, similar structure
    - verifyWebhook        # Webhook verification (different event types per integration)
    - parseWebhookUnsafe   # Webhook parsing (different event types per integration)
    - queryTasks           # Task query pattern (different response types)

  # ==========================================================================
  # PROJECT-SPECIFIC: Exports for future use or external consumption
  # ==========================================================================
  exports:
    - generateSecureToken        # Security utility for future use
    - WorkflowDefinitionMinimal  # Type used by getWorkflowId

  # ==========================================================================
  # PROJECT-SPECIFIC: Additional paths beyond framework patterns
  # ==========================================================================
  paths:
    - "**/seo-data.ts"           # Future feature - SEO/AEO configuration
    - "**/pricing-constants.ts"  # Future feature - pricing tiers
    - "**/openapi/generate.ts"   # OpenAPI generator script
    - "**/validate-svg.js"       # Asset validation script

  # ==========================================================================
  # PROJECT-SPECIFIC: Intentional duplicate pairs
  # ==========================================================================
  duplicate_pairs:
    # HubSpot search actions - different CRM objects, same pattern
    - ["packages/integrations/src/hubspot/actions/search-contacts.ts",
       "packages/integrations/src/hubspot/actions/search-deals.ts"]

report:
  format: markdown
  include_suggestions: true
  group_by: package
